User Authentication/AspNetAuth.WebApp/ViewModels/BaseViewModel.cs
namespace AspNetAuth.WebApp.ViewModels
{
    public class BaseViewModel
    {
        public string ErrorMessage { get; set; }
    }
}

User Authentication/AspNetAuth.WebApp/ViewModels/ErrorViewModel.cs
namespace AspNetAuth.WebApp.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

User Authentication/AspNetAuth.WebApp/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetAuth.WebApp.ViewModels
{
    public class LoginViewModel : BaseViewModel
    {
        [EmailAddress]
        [Required(ErrorMessage = "Email is required")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [MinLength(6, ErrorMessage = "Minimum password length is 6 characters")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Role is required")]
        public string Role { get; set; }
    }
}

User Authentication/AspNetAuth.WebApp/ViewModels/NewBlogViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetAuth.WebApp.ViewModels
{
    public class NewBlogViewModel : BaseViewModel
    {
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Body is required")]
        public string Body { get; set; }
    }
}

User Authentication/AspNetAuth.WebApp/ViewModels/UsersListViewModel.cs
using System.Collections.Generic;
using AspNetAuth.Shared.Classes.Response;

namespace AspNetAuth.WebApp.ViewModels
{
    public class UsersListViewModel : BaseViewModel
    {
        public List<UserDto> Users { get; set; }
    }
}

User Authentication/AspNetAuth.WebApp/Controllers/AuthController.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using AspNetAuth.Shared.Classes;
using AspNetAuth.Shared.Classes.Request;
using AspNetAuth.WebApp.Constants;
using AspNetAuth.WebApp.Interfaces;
using AspNetAuth.WebApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AspNetAuth.WebApp.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;
        private readonly JwtConfig _jwtConfig;

        public AuthController(IUserService userService, JwtConfig jwtConfig)
        {
            _userService = userService;
            _jwtConfig = jwtConfig;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var loginResult = await _userService.Login(new LoginUserRequest
                    {
                        Email = viewModel.Email,
                        Password = viewModel.Password,
                        Role = viewModel.Role
                    });

                    // Save JWT token to cookie
                    Response.Cookies.Append(Defaults.AccessTokenCookieKey, loginResult.AccessToken, new CookieOptions
                    {
                        Expires = DateTime.Now.AddSeconds(_jwtConfig.Lifetime),
                        HttpOnly = true,
                        Secure = true,
                        SameSite = SameSiteMode.Lax
                    });

                    return RedirectToAction("Index", "Home");
                }
                catch (HttpRequestException ex)
                {
                    viewModel.ErrorMessage = ex.Message;
                }
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Logout()
        {
            // Remove JWT token from cookie
            Response.Cookies.Delete(Defaults.AccessTokenCookieKey);

            return RedirectToAction("Index", "Home");
        }
    }
}

User Authentication/AspNetAuth.WebApp/Controllers/BlogsController.cs
using System.Net.Http;
using System.Threading.Tasks;
using AspNetAuth.Shared.Classes.Request;
using AspNetAuth.Shared.Models;
using AspNetAuth.WebApp.Interfaces;
using AspNetAuth.WebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetAuth.WebApp.Controllers
{
    [Authorize]
    public class BlogsController : Controller
    {
        private readonly IBlogService _blogService;

        public BlogsController(IBlogService blogService)
        {
            _blogService = blogService;
            
        }
        
        [Authorize(Roles = Role.User)]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = Role.Admin)]
        public IActionResult All()
        {
            return View();
        }

        [Authorize(Roles = Role.User)]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = Role.User)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveBlog(NewBlogViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _blogService.CreateBlogPost(new CreateBlogPostRequest
                    {
                        Title = viewModel.Title,
                        Body = viewModel.Body
                    });

                    return RedirectToAction("Index");
                }
                catch (HttpRequestException ex)
                {
                    viewModel.ErrorMessage = ex.Message;
                }
            }

            return View("New", viewModel);
        }
    }
}

User Authentication/AspNetAuth.WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using AspNetAuth.WebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AspNetAuth.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

User Authentication/AspNetAuth.WebApp/Controllers/UsersController.cs
using System.Net.Http;
using System.Threading.Tasks;
using AspNetAuth.Shared.Models;
using AspNetAuth.WebApp.Interfaces;
using AspNetAuth.WebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetAuth.WebApp.Controllers
{
    [Authorize(Roles = Role.Admin)]
    public class UsersController : Controller
    {
        private readonly IUserService _userService;

        public UsersController(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userService.GetAllUsers();
            return View(new UsersListViewModel
            {
                Users = users
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetUserStatus(string id, [FromQuery] bool active)
        {
            try
            {
                await _userService.ChangeUserActiveStatus(id, active);
                return RedirectToAction("Index");
            }
            catch (HttpRequestException ex)
            {
                return View("Index", new UsersListViewModel
                {
                    ErrorMessage = ex.Message
                });
            }
        }
    }
}

User Authentication/AspNetAuth.WebApp/Views/Blogs/All.cshtml
@{
    ViewData["Title"] = "All Blogs";
}

<h1 class="mb-4">All Blogs</h1>

<div class="blog-list-container">
    <p>Loading...</p>
</div>

@section Scripts
{
    <script src="~/js/blogs.js" asp-append-version="true"></script>
}

User Authentication/AspNetAuth.WebApp/Views/Blogs/Index.cshtml
@{
    ViewData["Title"] = "My Blogs";
}

<h1 class="mb-3">My Blogs</h1>
<a role="button" class="btn btn-primary mb-4" asp-controller="Blogs" asp-action="New">
    Add New Blog
</a>

<div class="blog-list-container">
    <p>Loading...</p>
</div>

@section Scripts
{
    <script src="~/js/blogs.js" asp-append-version="true"></script>
}

User Authentication/AspNetAuth.WebApp/Views/Blogs/New.cshtml
@model AspNetAuth.WebApp.ViewModels.NewBlogViewModel

@{
    ViewData["Title"] = "New Blog";
}

<h1 class="mb-4">New Blog</h1>

<form asp-action="SaveBlog">
    @if (Model?.ErrorMessage != null)
    {
        <div class="alert alert-danger mb-4" role="alert">
            @Model.ErrorMessage
        </div>
    }
    
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Body" class="control-label"></label>
        <input asp-for="Body" class="form-control" />
        <span asp-validation-for="Body" class="text-danger"></span>
    </div>
    <div class="form-group mt-5">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

User Authentication/AspNetAuth.WebApp/Views/Home/Index.cshtml
@using System.Security.Claims
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    @if (User.Identity.IsAuthenticated)
    {
        <h1 class="display-4">Welcome, @User.FindFirstValue(ClaimTypes.Name)</h1>
        <p>Your email is <strong>@User.FindFirstValue(ClaimTypes.Email)</strong></p>
    }
    else
    {
        <h1 class="display-4">Welcome</h1>
        <p>Please login to use the App</p>
    }
</div>

User Authentication/AspNetAuth.WebApp/Views/Shared/_Layout.cshtml
@using AspNetAuth.Shared.Models
@using System.Security.Claims
@using Newtonsoft.Json
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>@ViewData["Title"] - AspNetAuth</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetAuth</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            
                            @if (User.IsInRole(Role.Admin))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">All Users</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Blogs" asp-action="All">All Blogs</a>
                                </li>
                            }
                            else if (User.IsInRole(Role.User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Blogs" asp-action="Index">My Blogs</a>
                                </li>
                            }
                        </ul>
                        <ul class="navbar-nav">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <form asp-controller="Auth" asp-action="Logout">
                                        <button class="btn btn-link text-dark" type="submit">Logout</button>
                                    </form>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - AspNetAuth
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        
        <script type="text/javascript">
            GlobalVars.isAuthenticated = "@(User.Identity.IsAuthenticated)" === "True"
            GlobalVars.userRoles = @Html.Raw(JsonConvert.SerializeObject(User.Claims
                                       .Where(x => x.Type == ClaimTypes.Role)
                                       .Select(x => x.Value)))
        </script>

        @RenderSection("Scripts", false)
    </body>
</html>

User Authentication/AspNetAuth.WebApp/Views/Users/Index.cshtml
@model AspNetAuth.WebApp.ViewModels.UsersListViewModel

@{
    ViewData["Title"] = "All Users";
}

<h1 class="mb-5">All Users</h1>

@if (Model.ErrorMessage != null)
{
    <div class="alert alert-danger mb-5" role="alert">
        @Model.ErrorMessage
    </div>
}

<form id="set-user-status-form" method="post">
</form>

<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Display Name</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">Active</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var (item, index) in Model.Users.Select((value, idx) => (value, idx + 1)))
    {
        <tr>
            <td><strong>@index</strong></td>
            <td>@item.DisplayName</td>
            <td>@item.Email</td>
            <td>@item.Role</td>
            <td>@(item.Active ? "Yes" : "No")</td>
            <td>
                <button data-user-id="@item.Id" data-user-active="@item.Active" class="btn btn-outline-danger block-unblock-btn">
                    @(item.Active ? "Block" : "Unblock")
                </button>
            </td>
        </tr>
    }
    </tbody>
</table>

@section Scripts
{
    <script src="~/js/pages/users-list/index.js" asp-append-version="true"></script>
}